// To avoid adding a lot of boilerplate, locale packs are
// automatically generated here. These are written into the tmp/
// directory and then used to generate locale_en.js, locale_fr.js, etc.

const fs = require('fs');
const path = require('path');
const rimraf = require('rimraf');
const mkdirp = require('mkdirp');

const localesJsonPath = path.join(__dirname, '../../app/javascript/mastodon/locales');
const locales = fs.readdirSync(localesJsonPath).filter(filename => {
  return /\.json$/.test(filename) &&
    !/defaultMessages/.test(filename) &&
    !/whitelist/.test(filename);
}).map(filename => filename.replace(/\.json$/, ''));

const customLocalesJsonPath = path.join(localesJsonPath, 'custom');
const customLocales = fs.readdirSync(customLocalesJsonPath).filter(filename => {
  return /\.json$/.test(filename);
}).map(filename => filename.replace(/\.json$/, ''));

const outPath = path.join(__dirname, '../../tmp/packs');

rimraf.sync(outPath);
mkdirp.sync(outPath);

const outPaths = [];

[...locales, ...customLocales].forEach(locale => {
  const localePath = path.join(outPath, `locale_${locale}.js`);
  const baseLocale = locale.split('-')[0]; // e.g. 'zh-TW' -> 'zh'
  const localeDataPath = [
    // first try react-intl
    `../../node_modules/react-intl/locale-data/${baseLocale}.js`,
    // then check locales/locale-data
    `../../app/javascript/mastodon/locales/locale-data/${baseLocale}.js`,
    // fall back to English (this is what react-intl does anyway)
    '../../node_modules/react-intl/locale-data/en.js',
  ].filter(filename => fs.existsSync(path.join(outPath, filename)))
    .map(filename => filename.replace(/..\/..\/node_modules\//, ''))[0];
  const customLocaleDataPath = [
    `../../app/javascript/mastodon/locales/custom/locale-data/${baseLocale}.js`,
  ].filter(filename => fs.existsSync(path.join(outPath, filename)))
    .map(filename => filename.replace(/..\/..\/node_modules\//, ''))[0];

  let localeContent = `//
// locale_${locale}.js
// automatically generated by generateLocalePacks.js
//
import { setLocale, updateLocale } from '../../app/javascript/mastodon/locales';
import localeData from ${JSON.stringify(localeDataPath)};
`;

  const localeUnavailable = !locales.includes(locale);
  const customLocaleDataAvailable = customLocaleDataPath !== undefined;
  const customLocaleAvailable = customLocales.includes(locale);

  if (customLocaleDataAvailable)
    localeContent += `import customLocaleData from ${JSON.stringify(customLocaleDataPath)};\n`;

  if (localeUnavailable)
    localeContent += `import messages from '../../app/javascript/mastodon/locales/custom/${locale}.json'\n`;
  else {
    localeContent += `import messages from '../../app/javascript/mastodon/locales/${locale}.json'\n`;
    if (customLocaleAvailable)
      localeContent += `import customMessages from '../../app/javascript/mastodon/locales/custom/${locale}.json'\n`;
  }

  localeContent += 'setLocale({messages, localeData});\n';

  if (localeUnavailable && customLocaleDataAvailable)
    localeContent += 'updateLocale({messages: {}, localeData: customLocaleData});\n';
  else if (customLocaleAvailable) {
    if (customLocaleDataAvailable)
      localeContent += 'updateLocale({messages: customMessages, localeData: customLocaleData});\n';
    else
      localeContent += 'updateLocale({messages: customMessages, localeData: []});\n';
  }

  fs.writeFileSync(localePath, localeContent, 'utf8');
  outPaths.push(localePath);
});

module.exports = outPaths;


